# frozen_string_literal: true

source "http://rubygems.org"
ruby "2.5.1"

gem "activemodel"
gem "activesupport"
gem "addressable"
gem "browsermob-proxy"
gem "browserstack-local"
gem "byebug"
gem "cucumber"
gem "dotenv"
gem "em-http-request"
gem "google_drive"
gem "httparty"
gem "parallel_tests", "2.32.0"
gem "rake"
gem "report_builder"
gem "require_all"
gem "retriable"
gem "rspec", "3.6.0"
gem "rubocop"
# gem "screen-object"
gem "appium_lib", ">=10.3"
gem "aws-sdk"
gem "chunky_png"
gem "rspec_html_reporter"
gem "selenium-proxy"
gem "tty-prompt"
